# Copy and paste the code below into a ~/.bashrc, ~/.zshrc, ~/.profile, or ~/.zprofile, depending on which shell you use

# Setting PATH for Python 3.11
PATH="/Library/Frameworks/Python.framework/Versions/3.11/bin:${PATH}"
export PATH

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This 
loads nvm bash_completion
cd /path/to/project-folder && nvm use 16
