import React from 'react';
import { Card, Container, Row, Col } from 'react-bootstrap';

const Suggestions = ({ suggestions }) => {
  console.log(suggestions);
  if (suggestions.error) {
    return <div>{suggestions.error}</div>;
  }

  return (
    <Container className="mx-auto mt-4">
      <p className="mb-4">Suggestions are generated by ChatGPT. Check important info.</p>
      {Array.from({ length: Math.ceil(suggestions.expenses_advice.length / 4) }).map((_, rowIndex) => (
        <Row key={rowIndex} xs={1} sm={2} md={4} className="g-4 justify-content-center mb-3">
          {suggestions.expenses_advice
            .slice(rowIndex * 4, rowIndex * 4 + 4)
            .map((advice, index) => (
              <Col className="mb-2" key={index}>
                <Card className="h-100" border="dark" style={{ borderWidth: '2px' }}>
                  {advice.type === "Food" && (
                    <Card.Img variant="top" src="/images/food.png" />
                  )}
                  {advice.type === "Housing" && (
                    <Card.Img variant="top" src="/images/housing.png" />
                  )}
                  {advice.type === "Utilities" && (
                    <Card.Img variant="top" src="/images/utilities.png" />
                  )}
                  {advice.type === "Tuition" && (
                    <Card.Img variant="top" src="/images/tuition.png" />
                  )}
                  {advice.type === "Phone" && (
                    <Card.Img variant="top" src="/images/phone.png" />
                  )}
                  {advice.type === "Transportation" && (
                    <Card.Img variant="top" src="/images/transportation.png" />
                  )}
                  {advice.type === "Entertainment" && (
                    <Card.Img variant="top" src="/images/entertainment.png" />
                  )}
                  {advice.type === "Miscellaneous" && (
                    <Card.Img variant="top" src="/images/miscellaneous.png" />
                  )}
                  <Card.Header>{advice.type}</Card.Header>
                  <Card.Body className="d-flex flex-column justify-content-between">
                    <Card.Title>Classification: {advice.classification}</Card.Title>
                    <Card.Text>
                      <strong>Advice:</strong> {advice.advice}<br />
                    </Card.Text>
                  </Card.Body>
                </Card>
              </Col>
            ))}
        </Row>
      ))}
    </Container>
  );
};

export default Suggestions;



